### ISSUE TITLE
Not getting the sensor entities

### ISSUE THREAD

**Issue by BebeMischa** [Skons/hassio-addons#1]
Installed exactly, as the manual states.

Only new entities, I get, are update sensors and the automation.

![image](https://user-images.githubusercontent.com/73079275/125958995-34139938-e7f9-430a-b34b-d05d720998ea.png)

![image](https://user-images.githubusercontent.com/73079275/125959148-9792efee-9255-44c4-a766-973b069de64a.png)

But no entities to see the gas prices.

Running on HA supervised 2021.7.2, Docker, Debian 10, all up to date.

Logs after whole day running:

![image](https://user-images.githubusercontent.com/73079275/125959564-b47786fa-752f-493a-87a9-a527fe426cd8.png)

Core log:

```
2021-07-16 15:55:00 ERROR (SyncWorker_6) [homeassistant.components.python_script.dutch_gas_prices.py] Error executing script: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 221, in execute
    exec(compiled.code, restricted_globals)
  File "dutch_gas_prices.py", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by llewy** [comment]
Did you create a sensor?

https://github.com/skons/hassio-addons/blob/main/dutch_gas_prices/DOCS.md

**Comment by BebeMischa** [comment]
Yes, it's in configuration.yaml

**Comment by BebeMischa** [comment]
I think, I found a possible reason. I did dive into Portainer and see, that one of the images installed by the addon stays unused. There is no container made with that image.
So, i think, the installation process of this addon fails somewhere...

![image](https://user-images.githubusercontent.com/73079275/125992830-2c491e14-508e-4de4-8239-bbd646f8ecfc.png)

**Comment by Skons** [comment]
Before we dive into docker, which is not completely my expertise, i want to know a few things in regards to your container setup
1. Is it running? What does the log say when you go to the addon and you click logs?
2. If it is running, do you see requests coming in? You should see requests every hour.
3. is there a sensor named gas_stations_within_radius? and what is the state and what is in the attributes?

**Comment by Skons** [comment]
> 
> 
> I think, I found a possible reason. I did dive into Portainer and see, that one of the images installed by the addon stays unused. There is no container made with that image.
> So, i think, the installation process of this addon fails somewhere...
> 
> ![image](https://user-images.githubusercontent.com/73079275/125992830-2c491e14-508e-4de4-8239-bbd646f8ecfc.png)

I thought i could not explain this one, but it is an easy one. It is showing amd64 as unused and this is correct. It has downloaded the image and it is used as base for the DGP container. I followed the official guidelines and there is no mention of cleaning up those images. An unused image, i think, is not a problem.

**Comment by BebeMischa** [comment]
1.

![image](https://user-images.githubusercontent.com/73079275/125993905-0ccdd8cb-7ee7-4876-988b-aeefd6c0acc8.png)

2. Where do I check that?

3. Sensor in configuration.yaml:

```
  - platform: qbittorrent
    url: 'http://192.168.178.47:8080'
    username: XXXXX
    password: XXXXXX

  - platform: rest
    name: Gas stations within radius
    scan_interval: 600
    resource_template: http://homeassistant.local:5035/api/v1/gas_stations/euro98?radius=10&longitude={{ state_attr("zone.home", "longitude") }}&latitude={{ state_attr("zone.home", "latitude") }}
    method: GET
    json_attributes:
      - gas_stations
    value_template: >
      {% if (value_json.gas_stations[0].prijs) %}
        {{ value_json.gas_stations | length }}
      {% endif %}
      
# DLNA
discovery:
  enable:
    - dlna_dmr
```

4. All sensors containing "gas" 

![image](https://user-images.githubusercontent.com/73079275/125995017-852f620c-d2c6-438f-a15a-33aa3cbda824.png)

5. The log now shows more, than yesterday:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Dutch gas prices
 Get gas prices from dutch gas stations
-----------------------------------------------------------
 Add-on version: 2021.7.16.2
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.7.2
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:24:29] INFO: Starting dutch gas prices...
INFO:     Started server process [296]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5035 (Press CTRL+C to quit
```

So, the only thing missing, is the sensor...

I do not know much about Docker too, but I know, that this unused image has not been there yesterday. So I do think, that the addon tryed to install a container, but it failed... As this is my only Python based addon, I'm pretty sure, it somehow plays a role here...
