### ISSUE TITLE
Automation malformed

### ISSUE THREAD

**Issue by BebeMischa** [Skons/hassio-addons#10]
Thanks for the new update. Much appreciated!

Setup with Mosquitto were gone fine, no any issues.

Setting up the automation give's me error: ``` Message malformed: expected dictionary ``` and won't save.

```
- alias: Update gas stations
  trigger:
    - platform: time_pattern
      minutes: 5 #every 5 minute past whole
  action:
  - service: mqtt.publish
    data:
      topic: 'dgp/gas_stations'
      payload_template: '{"fuel_type":"euro98","radius":5,"latitude":{{ state_attr("person.mischa", "latitude") }},"longitude":{{ state_attr("person.mischa", "longitude") }}, "to_publish":10}'
```

Em I doing something wrong?

addon log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Dutch gas prices
 Get gas prices from dutch gas stations
-----------------------------------------------------------
 Add-on version: 2021.11.10.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.11.4
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:59:59] INFO: Log_level: info
[21:59:59] INFO: mqtt_host: core-mosquitto
[21:59:59] INFO: mqtt_port: 1883
[21:59:59] INFO: Starting dutch gas prices...
INFO:dgp_common:DGP initialized, launching client
INFO:dgp_common:Connecting mqtt
INFO:dgp_common:Connected with result code 0
```

**Comment by Skons** [comment]
The error did not show up on my HA instance, though the platform trigger was indented 1 too far. So here is the automation that fixes that issue

```
- alias: Update gas stations test
  trigger:
  - platform: time_pattern
    minutes: 5 #every 5 minute past whole
  action:
  - service: mqtt.publish
    data:
      topic: 'dgp/gas_stations'
      payload_template: '{"fuel_type":"euro95","radius":5,"latitude":{{ state_attr("person.skons", "latitude") }},"longitude":{{ state_attr("person.skons", "longitude") }}, "to_publish":3}'
```
`
