### ISSUE TITLE
installatie mislukt

### ISSUE THREAD

**Issue by mupsje** [Skons/hassio-addons#5]
while installing, I get:

The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies tesseract-ocr tesseract-ocr-dev jpeg-dev libjpeg zlib-dev gcc libc-dev linux-headers libffi-dev rust cargo openssl-dev && mkdir -p /app && mkdir -p /app/cache && pip3 install Pillow && pip3 install uvicorn fastapi requests requests[socks] requests[security] fake_headers pytesseract geopy && chmod a+x /run.sh' returned a non-zero code: 17

Please advice. 
Advies graag ;) 

Versie | core-2021.10.6
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Virtuele omgeving | false
Python-versie | 3.9.7
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.10.70
CPU-architectuur | x86_64

**Comment by Skons** [comment]
just to be sure, have you tried installing the addon multiple times? If so, and that has failed, or it keeps failing, can you run a debug installation? You will need to place the addon locally so i can provide you with a debug installation. This can be done through the smb addon for instance.

**Comment by mupsje** [comment]
Hello,

I tried on 4 differtent OS.
And all I get is a the same Failure. Again and Again,
Please try yourself to install on new HA.
You will get a error. You'll see.
Hope you will fix it.
Greets and nice weekend.

**Comment by Skons** [comment]
Issue is fixed with the latest version, @mupsje can you confirm?

**Comment by mupsje** [comment]
Hi, yes it installed now.
Thanks allot.

http://homeassistant.local:5035/docs is running good

But now I cannot see the sensor thatsis created in the yaml.

'sensor.gas_stations_within_radius'

```
- platform: rest
  name: 'gas_stations_within_radius'
  scan_interval: 7776000 
  timeout: 180
  resource_template: http://homeassistant.local:5035/api/v1/gas_stations/euro95?radius=5&longitude={{ state_attr("person.paula", "longitude") }}&latitude={{ state_attr("person.paula", "latitude") }}
  method: GET
  json_attributes:
    - gas_stations    
  value_template: >
    {{ value_json.gas_stations | length }}
```


Advice please?

Greets Remco
